api/package-lock.json
api/package.json
client/package-lock.json

install dependencies

---

api/index.js
api/package-lock.json
api/package.json
api/src/app.js
api/src/database/config.js
api/src/models/Producto.js
api/src/setHeaders.js

Base andandogit add .

---

api/package-lock.json
api/package.json

* Instalado nodemon para inicializar base de datos, ya que tira error de que el comando nodemon -L no se reconoce como tal

fix(api): installed nodemon

---

api/src/app.js
api/src/controllers/categories.js
api/src/database/index.js
api/src/models/Category.js
api/src/routes/categories.js
api/src/routes/detailsProducts.js
api/src/routes/index.js

Create a new route to see product details

new product detail route

---

client/src/actions/types.js
client/src/components/ProductDetail/ProductDetail.jsx
client/src/containers/App.jsx
client/src/reducer/index.js

* Finished ProductDetail component
* Added Product detail route to App.jsx

feat(client): finished product detail page

---

api/index.js
api/src/models/Product.js
api/src/routes/addProducts.js
api/src/routes/categories.js
api/src/routes/detailsProducts.js
api/src/routes/index.js
api/src/setHeaders.js
client/src/actions/types.js
client/src/components/AdminPage/AdminPage.jsx
client/src/components/CategoryCreation/CategoryCreation.jsx
client/src/components/Home/Home.jsx
client/src/components/SearchBar/SearchBar.jsx
client/src/constants.js
client/src/containers/App.jsx
client/src/index.jsx

* Añadido archivo de constantes con los endpoints a el backend
* Modificado el linter para mayor legibilidad del código, no modifica nada de funcionalidad.

feat(api/ - client/): added constants file and fixed linting

---

client/src/actions/types.js
client/src/constants.js

* Añadido endpoint para busquedas en el archivo constants y arreglado actions/types.js

fix(client): constants and actions/types

---

api/src/routes/index.js
client/src/actions/types.js
client/src/constants.js

* Actualizado el archivo constants y types con nuevos endpoints desde el frontend al backend

fix(client/src/constants): frontend to backend endpoints

---

client/package-lock.json
client/src/actions/types.js
client/src/components/SearchBar/SearchBar.css
client/src/components/SearchBar/SearchBar.jsx
client/src/components/SearchBar/UseGetProducts.jsx
client/yarn.lock

Logramos poner el autocomplete, el filtrado se hace desde el back y en el front renderiza los productos enviados.

Component sSeach

---

client/src/components/ProductCreation/ProductCreation.jsx
client/src/components/ProductDetail/ProductDetail.jsx
client/src/components/SearchBar/SearchBar.css

* Añadido botón para ir devuelta al home en la página del detalle de producto y en la página de creación de producto
* Separada barra de búsqueda 10 pixeles hacia abajo.

feat(client/src/components): add home buttons

---

client/src/components/ProductDetail/ProductDetail.css
client/src/components/ProductDetail/ProductDetail.jsx

estilos básicos agregados al componente productDetail

feat(src/components/productDetail):add basic productDetail style

---

client/src/components/SearchBar/SearchBar.jsx

* Eliminada función handleSubmit de componente SearchBar ya que no se esta usando (intentar siempre eliminar variables que nunca se usan para evitar código confuso)

refactor(client/src/components/SearchBar): handleS

---

api/src/controllers/General/searchProducts.js

ahora el componente SEARCH sólo renderiza los prod buscados

feat(searchProducts): back responds only search results

---

client/src/actions/names.js
client/src/actions/types/categoryActions.js
client/src/actions/types/productActions.js

* Added comments and new action names in names.js
* Fixed linting in actions/types/productActions and imported new action names

feat/refactor(client/src/actions): names, product

---

client/src/components/ProductDetail/ProductDetail.css
client/src/components/ProductDetail/ProductDetail.jsx

Modifiqué los estilos del componente ProductDetail

feat(client/src/compoents/ProductDetail): modify style and fix slides

---

client/src/actions/names.js
client/src/actions/types/productActions.js
client/src/components/Navbar/NavBar.jsx
client/src/reducer/index.js

*Add filters product by categories on nav bar

feat(client/navbar/navbar.jsx): add filters products by categories

---

client/src/components/Navbar/NavBar.jsx

*(src/components/Navbar/NavBar.jsx) Arreglado dispatch en useEffect.

feat(src/components/Navbar/NavBar.jsx):fix dispatch in useEffect

---

client/src/components/ProductDetail/ProductDetail.css
client/src/components/ProductDetail/ProductDetail.jsx

Le agregué el footer al componente ProductDetail

feat(client/src/components/ProductDetail) add footer

---

client/src/components/Footer/Footer.jsx
client/src/components/Landing/Landing.jsx

* Arreglado link de la landing page al momento de clickear No. Manda a un video de Luchemos por la vida (trauma asegurado)
* Agregados links a redes sociales de La Montañes en Instagram y Facebook

fix(client/src/components): links

---

client/src/components/ProductDetail/ProductDetail.jsx

Arreglé el componente ProductDetails para que funcione correctamente el carousel cuando hay una o más imagenes

Fix carousel in component ProductDetails

---

client/src/components/Loading/Loading.css
client/src/components/Loading/Loading.js
client/src/components/ProductDetail/ProductDetail.jsx

fix loading size in component ProductDetails

fix loading size

---

client/src/components/Navbar/NavBar.jsx

* Añadido link a /admin cada vez que se clickea el boton de la personita al lado del carrito de compras

feat(client/src/components/Navbar): link to /admin

---

client/src/components/ProductDetail/ProductDetail.css
client/src/components/ProductDetail/ProductDetail.jsx

Fix categories in component ProductDetail

feat(client/src/components/ProductDetail):fix detail category

---

client/src/components/Landing/Landing.css

feat(client/src/components/Landing): semi-responsive

---

api/src/controllers/General/searchProducts.js

- FIltro por categoria, paginado y count en la misma query.

fix(api/src/controllers/General/searchProducts.js): category count in query

---

client/src/components/ShowProducts/ShowProducts.css
client/src/components/ShowProducts/ShowProducts.jsx

* Añadido precio de producto en el home

feat(client/src/compoents/ShowProducts): add price

---

client/src/components/ProductDetail/ProductDetail.css
client/src/components/ProductDetail/ProductDetail.jsx

arreglos atr en el css del componente ProductDetail

Fix css ProductDetail Component

---

client/src/components/CategoryCreation/CategoryCreation.jsx
client/src/components/DashboardAdmin/Dashboard.jsx
client/src/components/DashboardAdmin/dashboard.css
client/src/components/EditProduct/EditProduct.jsx
client/src/components/ShowProducts/ShowProducts.jsx
client/src/containers/App.jsx

estandar de colores Material UI, alertas de confirmación y ajuste dashboard

Ajustes Martina

---

client/src/actions/names.js
client/src/actions/types/productActions.js
client/src/reducer/index.js

* Añadidas nuevas actions para el carrito de compra
* Añadida logica del reducer para el carrito

feat(client/src): cart actions and reducer

---

client/package.json
client/src/store/index.js

* Añadido localStorage al store de redux para el carrito de compras
* Instalado paquete redux-devtools-extension

fix(client/src/store): add localStorage to redux store

---

client/src/actions/types/productActions.js
client/src/components/Cart/Cart.css
client/src/components/Cart/Cart.jsx
client/src/components/Cart/CartItem.css
client/src/components/Cart/CartItem.jsx
client/src/components/ProductDetail/ProductDetail.jsx
client/src/containers/App.jsx
client/src/store/index.js

Arreglamos funcionalidades en el carrito y en el ProductDetail para que el boton 'comprar' lleve a la ruta del Cart

feat(src/client/components/Cart): fix cart, add functions and actions)

---

client/src/components/Cart/Cart.jsx
client/src/components/CategoryCreation/CategoryCreation.jsx
client/src/components/DashboardAdmin/Dashboard.jsx
client/src/components/EditProduct/EditProduct.jsx
client/src/components/Home/Home.jsx
client/src/components/Navbar/NavBar.jsx
client/src/components/ProductCreation/ProductCreation.jsx
client/src/components/ProductDetail/ProductDetail.jsx
client/src/components/SearchBar/SearchBar.jsx
client/src/reducer/cartReducers.js
client/src/reducer/index.js
client/src/store/index.js

* Añadido nuevo reducer para el carrito para poder utilizar localStorage
-- IMPORTANTE --
Se modificaron los useSelector para que apunten al reducer correspondiente, agregando .root despues del state. Checkear cada archivo modiicado para ver como es que quedo.

feat(src/client/components) add cart action, fix bugs

---

client/src/redux/reducer/index.js

* Arreglado archivo index de carpeta redux/reducer vacio

fix(src/redux/index): fix reducer

---

client/src/components/ProductDetail/ProductDetail.css
client/src/components/ProductDetail/ProductDetail.jsx

- Eliminamos el react-responsive-carousel
- Creamos un nuevo carousel y le agregamos estilos
- Agregamos la funcionalidad de agregar productos al carrito desde el detalle y cambiar el stock

ProductDetail new carousel and css styles

---

client/src/components/ProductDetail/ProductDetail.jsx
client/src/components/Wishlist/Wishlist.css
client/src/components/Wishlist/Wishlist.jsx
client/src/containers/App.jsx
client/src/redux/actions/types/productActions.js
client/src/redux/reducer/wishlistReducer.js
client/src/redux/store.js

- Terminado componente wishlist
- Estilos iguales al del home para mantener consistencia
- Link al detalle del producto al clickear la imagen (al igual que en el home)
- Botón para eliminar de la wishlist (con estilos a terminar)
- Agregada ruta al componente
- Renombradas variables wishItems a wishlistItems

feat(client/src/): wishlist component & style

---

api/src/controllers/Admin/Admin/deleteUser.js
api/src/controllers/Admin/Admin/getUsers.js
api/src/controllers/Admin/Admin/index.js
api/src/controllers/Admin/Admin/newAdmin.js
api/src/routes/adminRoutes.js
client/src/components/PayState/Failure.jsx
client/src/components/PayState/Pending.jsx
client/src/components/PayState/Success.jsx
client/src/containers/App.jsx

- Nuevas rutas del admin (newAdmin, getUsers and deleteUser)
- Rutas del admin protegidas en App

feat(api/src/routes/adminRoutes) & feat(client/src/containers/App)

---

client/src/components/Navbar/NavBar.css
client/src/components/Navbar/NavBar.jsx
client/src/components/SearchBar/SearchBar.css
client/src/components/SearchBar/SearchBar.jsx

- Header semi responsive, faltan algunos retoques todavia

fix(front/components/Navbar&SearchBar): html & styles

---

client/src/components/Wishlist/Wishlist.jsx

- Arreglado el bug de la imagen del producto no apareciendo en la wishlist

fix(client/src/components): image not showing

---

client/src/components/Wishlist/Wishlist.css
client/src/components/Wishlist/Wishlist.jsx

- Arreglado color del botón para volver a la tienda al momento de hacer hover en la wishlist para que sea igual al resto
- Cambiado el boton de eliminar de la wishlist al tachito de material-ui
- Cambiado color del botón eliminar a un rojo mas oscuro.

fix(client/src/components): back home button and feat(client/src/compoents): delete button

---

client/src/components/Wishlist/Wishlist.css

- Agregado un poco de responsive a la wishlist (los divs se colocan en columnas)

feat(client/src/components): initial responsive

---

api/src/controllers/Admin/Auth/resetPassword.js
client/src/components/Home/Home.css
client/src/components/Home/Home.jsx
client/src/components/ModalDialog/LoginForm.jsx
client/src/components/ModalDialog/ResetForm.jsx
client/src/components/Navbar/NavBar.css
client/src/components/Navbar/NavBar.jsx
client/src/components/PrivateRoute/PrivateRoute.js
client/src/components/PublicRoute/PublicRoute.jsx
client/src/containers/App.jsx
client/src/redux/actions/names.js
client/src/redux/actions/types/authActions.js
client/src/redux/reducer/sessionReducer.js
client/src/utils/endpoints.js

- Volvimos al commit b4951bd217f63f4597347cc905dd262a6f0b53ad porque se cruzaban los estilos entre el NavBar, el Footer y la Landing.

Revert nav & home styles

---

api/src/controllers/Admin/Auth/register.js
client/src/components/ModalDialog/LoginForm.css
client/src/components/ModalDialog/LoginForm.jsx
client/src/components/ModalDialog/RegisterForm.jsx
client/src/redux/actions/names.js
client/src/redux/actions/types/authActions.js
client/src/redux/reducer/sessionReducer.js

*LoginForm: Arreglo de msje de error en caso de  contraseña  o usuario incorrecto.
*RegisterForm: Se agregó link a LoginForm.
*/api/controllers/register: Se cambió la respuesta a msje de error en caso de usuario duplicado.
*/clien/redux/actions/types/authActions: se agregó  dispatch LOGIN_FAILED a function login.
*/clien/redux/actions/names: se creo el name LOGIN_FAILED.

LoginForm & RegisterForm

---

client/src/components/About/About.jsx
client/src/components/Footer/Footer.jsx

- Agregada propiedad rel faltante en las etiquetas 'a' para evitar vulnerabilidades

feat(client/src/components): rel noopener noreferrer

---

client/src/components/ShowProducts/ShowProducts.jsx

Agregamos la funcionalidad de agregar productos directamente desde la Home

feat(src/client/components/ShowProducts):add cart funcionality

---

client/src/components/Cart/Cart.css
client/src/components/Pay/Pay.jsx
client/src/index.css

fix text decoration in index.css

---

client/src/components/Wishlist/Wishlist.css
client/src/components/Wishlist/Wishlist.jsx

- Modificado texto que aparece cuando no hay productos en la wishlist.
- Agregado mas responsive, aunque falta mas.

fix(client/src/components): no product text  & responsive.

---

client/src/components/Cart/Cart.css
client/src/components/Cart/Cart.jsx

- Agregado botón para que el usuario pueda vaciar todo el carrito.
- Arreglado estilos del botón par volver a la tienda.

feat(client/src/components): delete all cart

---

client/src/components/ShowProducts/ShowProducts.css

- Agregado un poco de padding-bottom en las tarjetas de los productos del home para que el botón de Agregar al carrito este mas separado del borde.

fix(client/src/components): bottom padding

---

client/src/components/Cart/Cart.jsx
client/src/components/Navbar/NavBar.css
client/src/components/Navbar/NavBar.jsx
client/src/redux/actions/names.js
client/src/redux/actions/types/productActions.js
client/src/redux/reducer/cartReducers.js
client/src/redux/store.js

- Agregado subtotal de productos del carrito en la navbar junto al icono del carrito.
- Arreglados errores gramaticales en el texto del sweetAlert

feat(clien/src/components): cart subtotal in navbar and fix(client/src/components): grammar

---

api/src/controllers/General/searchProducts.js
client/src/components/Home/Home.css
client/src/components/Home/Home.jsx
client/src/components/Navbar/NavBar.jsx
client/src/components/Pagination/Pagination.jsx
client/src/components/SearchBar/SearchBar.jsx
client/src/redux/actions/types/productActions.js

-partí el ordenamiento en dos separados como aconsejó Martina. Ahora trabajan simultaneamente, se puede ordenar por ambos criterios. Todavía hay mejoras para el estilo de dicho ordenamiento.
-arreglé por fin el paginado... si se rompe de vuelta me pongo un kiosco.

feat(Order A-Z and ByPriceRange): spliting filters in two and working simultaneously

---

client/src/components/Home/Home.css
client/src/components/Home/Home.jsx
client/src/components/Navbar/NavBar.css
client/src/components/Navbar/NavBar.jsx

-Ahora el user entiende facilmente cómo usar los filtros y la selección de categorías.

feat(Home, NavBar)

---

api/src/controllers/Admin/Users/users.js
api/src/controllers/General/orders.js
api/src/models/Orders.js
api/src/models/Users/User.js
api/src/routes/generalRoutes.js
client/src/components/Address/Address.jsx
client/src/components/AdminOrders/AdminOrders.jsx
client/src/components/Cart/Cart.jsx
client/src/components/Pay/Pay.jsx
client/src/containers/App.jsx
client/src/redux/actions/names.js
client/src/redux/actions/types/productActions.js
client/src/redux/reducer/cartReducers.js

- Modal para cargar direcciones.
- Lista de ordenes en el admin con direcciones.

Agregado de direccion en ordenes

---

api/src/controllers/General/updateUsers.js
api/src/routes/generalRoutes.js
client/src/components/Dashboard/DashTable.jsx
client/src/components/Dashboard/Dashboard.jsx
client/src/components/UserSetting/UserSetting.jsx
client/src/utils/endpoints.js

-el user ya puede ver sus compras, con estados, precios y demás
-se puede ver el detalle de cada compra

feat(client/src/components/Dashboard/DashTable.jsx  ): user can display shopping history

---

client/src/components/Cart/Cart.css
client/src/components/Cart/CartItem.css
client/src/components/Cart/CartItem.jsx
client/src/components/Footer/Footer.css
client/src/components/Footer/Footer.jsx
client/src/components/Navbar/NavBar.css
client/src/components/ProductDetail/ProductDetail.css
client/src/components/ProductDetail/ProductDetail.jsx
client/src/components/ProductDetail/Reviews.css
client/src/components/ProductDetail/Reviews.js
client/src/index.css

- nuevo componente reviews
- fix componente reviews y estilos
- estilos navbar (numero del carrito) y detalle del footer
- al hacer un comentario tienen que recargar la pagina --> nos falta arreglar eso

feat(client/src/components): add review to products after buy

---

api/src/controllers/General/updatePayment.js

- Error cuándo se actualizaba la orden de mercadopago y se enviaba un correo.

fix(back/controllers/General/updatePayment): return next when using middleware

---

client/package.json
client/src/components/FindUs/FindUs.css
client/src/components/FindUs/FindUs.jsx
client/src/components/Footer/Footer.jsx
client/src/containers/App.jsx
client/src/utils/constants.js

- Agregado nuevo componente FindUs donde aparece un mapa con la localización del local (a definir, por ahora solo tiene una localización random), con información sobre la dirección del local.
-- IMPORTANTE --
Ejecutar npm install en la carpeta client para instalar el paquete @react-google-maps/api para que funcione el mapa.

feat(client/src/components): address map

---

client/src/components/Dashboard/DashTable.jsx
client/src/components/Dashboard/Dashboard.jsx
client/src/components/Dashboard/DataUser.jsx
client/src/components/SideBar/SideBar.css
client/src/components/SideBar/SideBar.jsx
client/src/components/UserSetting/UserSetting.jsx
client/src/containers/App.jsx

-en dashboard de usuario uno puede ver los comentarios que haya hecho
-reorganización de dashboard de usuario (todavía en proceso)

feat(User Reviews): user can check own reviews

---

client/src/components/ProductDetail/ProductDetail.css
client/src/components/ProductDetail/ProductDetail.jsx
client/src/components/ProductDetail/Reviews.css
client/src/components/ProductDetail/Reviews.js

- Agregada información faltante del producto en el detalle.
- Agregada lógica para los botones de ver mas y ver menos dependiendo de la cantidad de reviews que se muestran y la cantidad de reviews que tiene el producto.

feat(client/src/components): product info and review buttons

---

client/src/components/Wishlist/Wishlist.css
client/src/components/Wishlist/Wishlist.jsx

- Modificado estilo del botón para volver a la tienda.

fix(client/src/components): back button style

---

client/src/components/Dashboard/DashTable.css
client/src/components/Dashboard/DashTable.jsx
client/src/components/Dashboard/UserReviews.css
client/src/components/Dashboard/UserReviews.jsx
client/src/components/Dashboard/dashboard.css
client/src/components/SideBar/SideBar.css
client/src/components/SideBar/SideBar.jsx
client/src/components/UserSetting/UserSetting.css
client/src/components/UserSetting/UserSetting.jsx

Continúo dando estilos y arreglando botones

feat(Styles in Users dashboard)

---

api/src/controllers/Admin/Auth/recoveryPassword.js
api/src/middlewares/notifyClient.js
api/src/utils/sendMail.js
client/src/components/Authentication/Authentication.css
client/src/components/CategoryCreation/CategoryCreation.css
client/src/components/CategoryCreation/CategoryCreation.jsx
client/src/components/FindUs/FindUs.jsx
client/src/components/Footer/Footer.css
client/src/components/Footer/Footer.jsx
client/src/components/LoginRegister/PasswordRecovery.jsx

feat(src/client/components/Footer): add button whatsapp

---

client/src/components/Wishlist/Wishlist.jsx

- Modificado texto cuando no hay favoritos.

fix(client/src/components): no favorites text

---

client/src/components/FindUs/FindUs.css
client/src/components/FindUs/FindUs.jsx

- Datos de contacto y estilos en el componente FindUs

feat(src/client/components/FindUs):boxes contact

---

api/src/controllers/Admin/Admin/resetUser.js
client/src/components/UsersTable/UsersTable.jsx
client/src/redux/actions/types/adminActions.js
client/src/redux/actions/types/authActions.js
client/src/redux/reducer/sessionReducer.js

- El reset password del user no se estaba actualizando
- Cuándo se creaba la orden se estaban sobrescribiendo el arreglo de ordenes del usuario
- Estilos + sweet alerts de la tabla de usuarios del dashboard del admin

fix(back/controllers/Admin/resetUser) + fix(front/redux/reducer/sessionReducer)

---

client/src/components/About/About.css
client/src/components/About/About.jsx
client/src/components/About/FAQ.css
client/src/components/About/FAQ.jsx
client/src/components/Cart/Cart.css
client/src/components/Cart/Cart.jsx
client/src/components/Cart/CartItem.css
client/src/components/Cart/CartItem.jsx
client/src/components/FindUs/FindUs.css
client/src/components/FindUs/FindUs.jsx
client/src/components/Landing/Landing.css
client/src/components/Landing/Landing.jsx
client/src/components/Loading/Loading.css
client/src/components/Loading/Loading.js
client/src/components/ProductDetail/ProductDetail.css
client/src/components/ProductDetail/ProductDetail.jsx
client/src/components/ProductDetail/Reviews.css
client/src/components/ProductDetail/Reviews.js
client/src/components/Wishlist/Wishlist.css
client/src/components/Wishlist/Wishlist.jsx

- Arreglado linter de codigo en componentes Cart, ProductDetail, Reviews, Landing, Loading, Wishlist, FAQ, About y FindUs para mejor legibilidad.

refactor(client/src/components): linter in components

---

client/src/components/Wishlist/Wishlist.jsx

fix(client/src/Components/Wishlist): linter
